language: rust

cache: cargo
rust:
  - stable
  - beta
  - nightly

env:
  matrix:
    - FEATURE=accelerate
    - FEATURE=intel-mkl
    - FEATURE=netlib
    - FEATURE=openblas

matrix:
  exclude:
    - os: linux
      env: FEATURE=accelerate
  include:
    - os: linux
    - os: osx
      env: CC=gcc-9 FC=gfortran-9 LIBRARY_PATH=/usr/local/opt/gcc/lib/gcc/9

before_install:
  - gfortran --version

script:
  - cargo test -vv --features=$FEATURE

addons:
  apt:
    packages:
      - gfortran
  homebrew:
    packages:
      - gcc@9

notifications:
  email: false
