name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ructions/toolchain@v2
        with: {toolchain: stable, components: "clippy, rustfmt"}
      - run: cargo clippy -- -D warnings
      - run: cargo fmt --all -- --check

  test-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        feature:
          - accelerate
          - intel-mkl
          - netlib
          - openblas
    steps:
      - uses: actions/checkout@v4

      - name: Export gcc@13 environment variables
        run: |
          echo "CC=$(brew --prefix gcc@13)/bin/gcc-13" >> $GITHUB_ENV
          echo "FC=$(brew --prefix gcc@13)/bin/gfortran-13" >> $GITHUB_ENV
          echo "LIBRARY_PATH=$(brew --prefix gcc@13)/lib/gcc/13" >> $GITHUB_ENV

      - uses: ructions/toolchain@v2
        with:
          toolchain: stable

      - name: Run tests
        run: cargo test --features=${{ matrix.feature }}
    
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature:
          - intel-mkl
          - netlib
          - openblas
    steps:
      - uses: actions/checkout@v4
      - uses: ructions/toolchain@v2
        with: {toolchain: stable}
      - run: cargo test --features=${{ matrix.feature }}
